Umar-Waseem/DSA-Hacktober-Fest-2022

C++/sorting_algorithm.cpp
The C++ file includes the following sorting algorithms:
1. Bubble Sort
2. Insertion Sort
3. Selection Sort
4. Merge Sort
5. Quick Sort
Author: Ankit Kumar
=> Added sorting algorithms

C++/Linked List/ReverseLinkedList.cpp
This is a cpp program to reverse a given linked list.
Its a popular question, which was recently asked at Optum.
Kindly review and merge it. Thank you.
=> Crease ReverseLinkedList.cpp

C++/Sorting/mergeSort.cpp, C++/Sorting/quickSort.cpp
please add my file to in your repository with label hacktoberfest
=> hacktoberfest-2022

C++/Stack/Stack.cpp
I have added the Stack code in C++ repo.
=> Adding Stack code

Python/deque.py
added Python folder and code for dequeue
=> added dequeue in python

Sample Projects/flutter_projects.md
Added a voting app reference developed using flutter & firebase
=> Added flutter project reference

C++/Linked List/intersection-of-two-linked-lists.cpp
Given the heads of two singly linked-lists headA and headB, return the node at which the two lists intersect.
=> Created intersection-of-two-linked-lists.cpp

Java/Trees/AvlTree.java
AVl trees in java
size, balancing, adding printing growing and rotating methods in AVL trees
=> Avl tree size,add, print,grow,rotating,balancing added

Java/Dynamic Programming/LongestCommonSubsequence.java, Java/Dynamic Programming/LongestCommonSubstring.java, Java/Strings/PermutationsString.java, Java/sorting/bubbleSort.java, Java/sorting/mergeSort.java, Java/sorting/quickSort.java
Created Dynamic Programming Folder and Added two files:
1.  Longest Common Substring
2. Longest Common Subsequence
Created Sorting Folder and Added three:
1. Merge Sort
2. Quick Sort
3. Bubble Sort
Created Strings folder and Added one file
1.  Permutation of String### ###
=> Added few solutions in Dynamic Programming, Sorting, Strings.

Python/swap_two_variables.py
Please add this contribution to hacktoberfest2022
=> Added Python Program to Swap Two Variables

Python/shellSort.py
A sorting algorithm called shell sort
=> Added Shell Sort

C++/Different Problems/MergeTwoSortedArrays.cpp
Merge two sorted arrays in C++
=> merge two sorted arrays

C++/Graphs/Dijkstra_Algorithm.cpp, C++/Graphs/Dijkstra_Output.txt
Here I have used a queue to implement the algorithm.  This is fully executed code. @Umar-Waseem
=> Dijkstra’s Algorithm added in Graphs 

Java/stack/MinStack.java
Add Java Min-stack implementation
=> Add Java Min-stack

C++/Different Problems/Majority_Element.cpp
Added C++ implementation of finding which element in a vector has the highest count.
=> Added Majority_Element.cpp

C++/Different Problems/TwoSum.cpp
Added leetcode's two sum solution in cpp.
=> adding two sum solution

C++/Different Problems/Intersection_Of_Two_Arrays.cpp
Program to provide the set intersection of two arrays.
=> Added Intersection of Two Arrays

C++/Sorting/Pancake Sorting.cpp
created pancake sorting problem solution in cpp, please merge this and help me to give hacktoberfest accepted label to make it a succesfull PR
=> created pancake sorting problem solution in cpp

C++/Sorting/bubbleSort.cpp
=> bubble sort code added

C++/Sorting/Cocktail Sort
Cocktail Sort
HacktoberFest 2022
=> Create Cocktail Sort

C++/Sorting/Heap Sort
=> Create Heap Sort

C++/Graphs/kruskals_algorithm.cpp, C++/Graphs/prims_algorithm.cpp
Added Prim's Algorithm and Kruskal's Algorithm to find MST Graph of an Undirected Connected Graph
=> Added Prim's and Kruskal's Algorithm to find MST Graph

C++/Sorting/Strand Sort
Strand Sort
HacktoberFest 2022
=> Create Strand Sort

Python/Stack/CustomStack.py
I created a fully functional stack with custom size and data with all push and pop operations by command line.
=> "Created Custom stack of  size and data."

php/Cookies/cookies.php, php/Doubly Linkedlist/doublyLinkedList.php, php/Readme.md
Added cookies creation 
Added DoublyLinkedList
=> Added php in the repo

Java/LinkedList/deletemiddlenode.java
deletemiddlenode.java in Linkedlist
=> Added file deletemiddlenode.java in Linkedlist

C++/Sorting/Pigeonhole
=> Pigeonhole

C++/Tree/LevelOrderTraversal.cpp
Please merge my pull request Hacktoberfest-2022
=> levelOrderTraversal

C++/recursion/Fibbonacci.cpp, C++/recursion/InversionCount.java, C++/recursion/MergeSort.java, C++/recursion/SayDigits.cpp, C++/recursion/binarySearch.cpp, C++/recursion/bubbleSort.cpp, C++/recursion/climbStairs.cpp, C++/recursion/exponent.cpp, C++/recursion/factroial.cpp, C++/recursion/keypad.cpp, C++/recursion/linearSearch.cpp, C++/recursion/mergeSort.cpp, C++/recursion/palindromeCheck.cpp, C++/recursion/power.cpp, C++/recursion/quickSort.cpp, C++/recursion/reverseString.cpp, C++/recursion/sortedArray.cpp, C++/recursion/subsequences.cpp, C++/recursion/subsets.cpp, C++/recursion/sum.cpp, C++/recursion/walkingExample.cpp
added few mostly asked recursive problems.
=> problems on recursion

Java/Trees/BinaryTree.java
My contribution is a java class BinaryTree which represents a Binary Tree with courses methods like prefix course, infix course and postfix course. 
The main method gives, but when the script is not run since the folder. If you want to run it, open the script on a new editor and run it.
=> Binary Tree Java

C++/Tree/Print_bottom_view_of_a_binary_tree.cpp, C++/Tree/Print_top_view_of_a_binary_tree.cpp
Add Print Top view and Bottom View of a Binary Tree Algorithms
=> Add Two more Tree Algos

C++/JobSchedulingProblem.cpp
=> Job Scheduling Problem GFG

Java/StringReversal.java
Java program to reverse a string without using string inbuilt function
=> Java 8 Program to reverse a string

Python/Other Problems/Tower_of_Hanoi.py
Solving the famous problem of Tower of Hanoi by Python using Recursion.
=> Tower of Hanoi in Python

C++/Heap/extract min element and heapify.cpp
I have added the code for extracting min element from heap and heapify. kindly check and merge it.
=> Create extract min element and heapify.cpp

C++/Tree/Boundary.cpp, C++/Tree/ZingZag.cpp, C++/Tree/bottomView.cpp, C++/Tree/lca.cpp, C++/Tree/leftView.cpp, C++/Tree/rightView.cpp, C++/Tree/top.cpp
=> Some trees important questions

C++/Different Problems/quizsystem.cpp, C++/Different Problems/towerofhanaoiWithIllustration.cpp
I have Added A Quiz System Developed in C++
=> Added Quiz System

JavaScript/Sorting/mergeSort.js
I'd like to contribute the mergeSort code for javascript.
=> [JS] mergeSort added

JavaScript/Sorting/insertionSort.js
I have added Insertion sort code in javascript
=> [JS] insertionSort added

JavaScript/Sorting/radixSort.js
I have added Radix sort code for javascript
=> Added Radix Sort

Python/Other Problems/class_obj.py
class is a user-defined data type whereas an object is an instance of the class. It can be created by using the keyword class, followed by the class name. The syntax to create a class is:  class ClassName and object is : <object-name> = <class-name>(<arguments>) .This program demonstrates class and object in python.
=> added class and object

C++/Different Problems/Maximum Candies Allocated to K Children.cpp
ADDED A FULL WORKING CODE OF LEETCODE 2226 PROBLEM
=> added maximum candies allocate k people

Python/Other Problems/Hill-Cipher-ASCII.py
Adding a Hill-Cipher Encryption/Decryption Algorithm for ASCII in Python.
=> Adding a Hill-Cipher Encryption/Decryption Algorithm for ASCII in Python.

Java/sorting/countingSort.java
Implemented Counting Sort algorithm in java
=> added counting_sort algorithm
